# Generated by Django 4.0.5 on 2022-06-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinosTuristicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=255)),
                ('descripcionCiudad', models.TextField()),
                ('imagenCiudad', models.ImageField(upload_to='pics')),
                ('precioTour', models.FloatField()),
                ('ofertaTour', models.BooleanField(default=False)),
            ],
        ),
    ]
